name: ZorroTracker GHA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 15.x

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install system dependencies [Linux]
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install \
          libasound2-dev \
          libpulse-dev \
          libjack-jackd2-dev

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Bodge node-gyp [Windows]
      if: runner.os == 'Windows'
      run: |
        npm cache clean --force

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run ci_init

    # Only macOS works for these tests
    # Flakey tests, may sometimes get stuck
    # Seems to be caused by Spectron specifically.
    # disabled for now, seriously can't take these flakey tests being flakey
    - name: Test [disabled]
      if: runner.os == 'not_macOS'
      run: npm run ci_test

    - name: Package artifact
      run: npm run ci_deploy

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ZorroTracker-${{ runner.os }}-${{ github.sha }}
        path: dist/ZorroTracker-*
